// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCGehjbCrWIxWYla44BEfMhs_fc0ywyM',
    appId: '1:117650384257:web:2683846423502542773480',
    messagingSenderId: '117650384257',
    projectId: 'praxis-backup-391009',
    authDomain: 'praxis-backup-391009.firebaseapp.com',
    storageBucket: 'praxis-backup-391009.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYFhq9bWCAHceVHRYEyEx62wgLcO6nGo',
    appId: '1:117650384257:android:f48e5024966672ac773480',
    messagingSenderId: '117650384257',
    projectId: 'praxis-backup-391009',
    storageBucket: 'praxis-backup-391009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpJCfFJVwFC0qludiD3z4Hi8l5cySRnc',
    appId: '1:117650384257:ios:0aabf785ba471711773480',
    messagingSenderId: '117650384257',
    projectId: 'praxis-backup-391009',
    storageBucket: 'praxis-backup-391009.appspot.com',
    iosBundleId: 'com.company',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyC3ZW7bHz-jy7Y7RIfwT1RDnLnSEJlJNL0',
  //   appId: '1:620522314877:ios:c23bb19c272b29a978e514',
  //   messagingSenderId: '620522314877',
  //   projectId: 'mis-lab-b6859',
  //   storageBucket: 'mis-lab-b6859.appspot.com',
  //   iosBundleId: 'mk.finki.ukim.mis.mis3.RunnerTests',
  // );
}